Utilize request sessions for ping identity provider plugin
aws/amazon-redshift-python-driver pull request #29
Opened 2021-03-30 22:17 UTC by daltonconley

## Description
Changes to the PingCredentialsProvider to utilize `requests` Sessions when making HTTP requests to Ping host.

## Motivation and Context
Some Ping implementations require cookies when making requests and those cookies need to be used when making subsequent requests to retrieve SAML. 

## Testing
- Unit tests passed. 
- Tested in a live environment with Ping and Redshift cluster.

## Screenshots (if appropriate)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Checklist
- [x] Local run of `python3 setup.py` succeeds
- [x] My code follows the code style of this project
- [x] I have read the **README** document
- [ ] I have added tests to cover my changes
- [x] All new and existing tests passed
- [x] A short description of the change has been added to the **CHANGELOG**

## License

- By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-04-02 18:11 UTC, daltonconley commented
@Brooke-white any feedback on this?

2021-04-02 21:48 UTC, Brooke-white commented
@daltonconley thank you for your patience. The team is in the process of conducting an internal review of these changes. We will provide you with feedback early next week, the week of April 5th.

2021-04-07 21:11 UTC, Brooke-white requested changes
Thank you for your contribution to `redshift_connector`, we appreciates the time you've taken to help improve our product. We would like to merge your PR pending the changes detailed.

2021-04-07 21:11 UTC, Brooke-white commented on redshift_connector/plugin/ping_credentials_provider.py
>          self.check_required_parameters()
```
self.check_required_parameters()

with requests.Session() as session:
  ...
```
using a `with` statement here will prevent resource leak.

2021-04-07 21:11 UTC, Brooke-white commented on CHANGELOG.md
No need to update the changelog, this occurs in an automated process when the team makes a release

2021-04-12 15:54 UTC, Brooke-white approved these changes

2021-04-12 15:55 UTC, merged